---
- name: test playbook
  hosts: web1
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  vars:
    ansible_ssh_private_key_file: /home/song/.ssh/recruit-ssh
  tasks:
    - name: copy
      copy :
        src: /home/song/ansible-setup/docker_install.sh
        dest: /home/songprem94/
      

    - name: command shell
      command: bash /home/songprem94/docker_install.sh
      
    
