---
- name: test playbook
  hosts: web1
  vars:
    ansible_ssh_private_key_file: /home/.ssh/{{ lookup('env','VM_SSH_KEY') }}
    remote_user_name: "{{ lookup('env', 'REMOTE_USER') }}"
  remote_user: "{{ remote_user_name }}"
  tasks:
    - name: copy docker install
      copy :
        src: /home/ansible-setup/docker_install.sh
        dest: /home/{{ remote_user_name }}/ansible-setup/
    - name : copy airflow docker compose file 
      copy :
        src : /home/ansible-setup/docker-compose.yaml
        dest : /home/{{ remote_user_name }}/ansible-setup/
    - name: copy install-allinone.sh
      copy :
        src: /home/ansible-setup/install-allinone.sh
        dest: /home/{{ remote_user_name }}/ansible-setup/

    - name: command shell
      command: bash /home/{{ remote_user_name }}/ansible-setup/install-allinone.sh
    
      
    
